module:
  addanother: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_direct_save: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_reference_views_select: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  filter: 0
  graphql: 0
  graphql_core: 0
  graphql_views: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  imce_rename_plugin: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  link: 0
  material_admin_support: 0
  media: 0
  menu_link_config: 0
  menu_ui: 0
  moderation_sidebar: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  profile: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  search: 0
  search_kint: 0
  settings_tray: 0
  shortcut: 0
  simple_block: 0
  svg_image_field: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  type_style: 0
  unified_twig_ext: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_devel: 0
  webform_image_select: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_templates: 0
  webform_ui: 0
  webform_views: 0
  workflows: 0
  yaml_content: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  emulsify: 0
  strik3: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
